var data = {
    "type":"FeatureCollection",
    "features":[
       {
          "type":"Feature",
          "geometry":{
             "type":"Point",
             "coordinates":[
                106.8397665024,
                -6.1751155028
             ]
          },
          "properties":{
             "pkey":"184076",
             "created_at":"2021-02-15T09:30:17.847Z",
             "source":"grasp",
             "status":"confirmed",
             "url":"d6b94b28-a06c-46f8-a63d-00fb15bfd935",
             "image_url":null,
             "disaster_type":"flood",
             "report_data":{
                "report_type":"flood",
                "flood_depth":105
             },
             "tags":{
                "district_id":"3173",
                "local_area_id":"757",
                "instance_region_code":"ID-JK"
             },
             "title":null,
             "text":"test"
          }
       },
       {
          "type":"Feature",
          "geometry":{
             "type":"Point",
             "coordinates":[
                106.8377923965,
                -6.1751368468
             ]
          },
          "properties":{
             "pkey":"184075",
             "created_at":"2021-02-15T09:29:42.768Z",
             "source":"grasp",
             "status":"confirmed",
             "url":"965717c1-8133-42d1-bac6-239d86771b66",
             "image_url":null,
             "disaster_type":"flood",
             "report_data":{
                "report_type":"flood",
                "flood_depth":103
             },
             "tags":{
                "district_id":"3173",
                "local_area_id":"756",
                "instance_region_code":"ID-JK"
             },
             "title":null,
             "text":"test"
          }
       }
    ]
 }